USE [Campus6_test]

DECLARE @p1 NVARCHAR(9) = '000165048'
DECLARE @p2 NVARCHAR(9) = '000165934'

SELECT P.PEOPLE_ID
	,P.PersonId
	,FIRST_NAME
	,LAST_NAME
	,UserName
	,NonQualifiedUserName
	,AU.OPERATOR_ID
	,AU.[STATUS]
FROM PersonUser
INNER JOIN PEOPLE AS P
	ON PersonUser.PersonId = P.PersonId
LEFT JOIN ABT_USERS AS AU
	ON AU.PEOPLE_CODE_ID = P.PEOPLE_CODE_ID
WHERE P.PEOPLE_ID IN (
		@p1
		,@p2
		);

SELECT DISTINCT AU.OPERATOR_ID
	,AUP.PROFILE_CODE
INTO #OpPerms
FROM PersonUser
INNER JOIN PEOPLE AS P
	ON PersonUser.PersonId = P.PersonId
LEFT JOIN ABT_USERS AS AU
	ON AU.PEOPLE_CODE_ID = P.PEOPLE_CODE_ID
LEFT JOIN ABT_USERPROFILE AS AUP
	ON AUP.OPERATOR_ID = AU.OPERATOR_ID
WHERE P.PEOPLE_ID IN (
		@p1
		,@p2
		);

--Operator Profile Diff
SELECT DISTINCT OP1.PROFILE_CODE
	,AP.PROFILE_NAME
	,CASE 
		WHEN OP2.PROFILE_CODE IS NULL
			THEN 'Only ' + OP1.OPERATOR_ID
		ELSE 'Both have'
		END [Status]
FROM #OpPerms OP1
LEFT JOIN ABT_PROFILE AS AP
	ON OP1.PROFILE_CODE = AP.PROFILE_CODE
LEFT JOIN #OpPerms OP2
	ON OP2.PROFILE_CODE = OP1.PROFILE_CODE
		AND OP2.OPERATOR_ID <> OP1.OPERATOR_ID;

--Offices
SELECT DISTINCT AU.OPERATOR_ID
	--,ifs.InquiryFormName
	--,ia.InquiryApproverId
	,abts.LABEL_NAME AS 'Office'
INTO #OpOffices
FROM PersonUser
INNER JOIN PEOPLE AS P
	ON PersonUser.PersonId = P.PersonId
LEFT JOIN ABT_USERS AS AU
	ON AU.PEOPLE_CODE_ID = P.PEOPLE_CODE_ID
--LEFT JOIN InquiryApprover AS ia
--	ON AUP.OPERATOR_ID = IA.OperatorId
--LEFT JOIN InquiryFormSetting ifs
--	ON ia.InquiryFormSettingId = ifs.InquiryFormSettingId
INNER JOIN ABT_SETTINGS abts
	ON AU.OPERATOR_ID = abts.SECTION_NAME
		AND SETTING = 'Y'
WHERE P.PEOPLE_ID IN (
		@p1
		,@p2
		)

SELECT DISTINCT OO1.Office
	,CO.SHORT_DESC
	,CASE 
		WHEN OO2.Office IS NULL
			THEN 'Only ' + OO1.OPERATOR_ID
		ELSE 'Both have'
		END [Status]
FROM #OpOffices OO1
LEFT JOIN CODE_OFFICE AS CO
	ON OO1.Office = CO.CODE_VALUE_KEY
LEFT JOIN #OpOffices OO2
	ON OO2.Office = OO1.Office
		AND OO2.OPERATOR_ID <> OO1.OPERATOR_ID;

SELECT NEWID() [Random Password];

DROP TABLE #OpPerms
	,#OpOffices;
