USE Campus6

--Status of row. C = completed, P = in progress, X = fell below minimum, Z = no status.
SELECT SDR.PEOPLE_CODE_ID
	,SDR.CURRICULUM
	,EVENT_CLASS
	,EVENT_ID
	,CASE SDE.[STATUS]
		WHEN 'C'
			THEN 'Complete'
		WHEN 'P'
			THEN 'In Progress'
		WHEN 'X'
			THEN 'Fail'
		WHEN 'Z'
			THEN NULL
		END AS [Status]
FROM STDDEGREQ SDR
INNER JOIN STDDEGREQEVENT SDE
	ON SDE.PEOPLE_CODE_ID = SDR.PEOPLE_CODE_ID
		AND SDE.PROGRAM = SDR.PROGRAM
		AND SDE.DEGREE = SDR.DEGREE
		AND SDE.CURRICULUM = SDR.CURRICULUM
		AND SDE.MATRIC_YEAR = SDR.MATRIC_YEAR
		AND SDE.MATRIC_TERM = SDR.MATRIC_TERM
		AND SDE.RECORD_TYPE = SDR.RECORD_TYPE
INNER JOIN ACADEMIC A
	ON A.PEOPLE_CODE_ID = SDR.PEOPLE_CODE_ID
		AND A.PROGRAM = SDR.PROGRAM
		AND A.DEGREE = SDR.DEGREE
		AND A.CURRICULUM = SDR.CURRICULUM
WHERE 1 = 1
	AND SDR.RECORD_TYPE = 'A'
	AND A.ACADEMIC_YEAR = '2021'
	AND ENROLL_SEPARATION = 'ENRL'
	AND ACADEMIC_FLAG = 'Y'
	--AND SDR.CURRICULUM = 'BS2010'
	AND [REQUIRED] = 'Y'
ORDER BY SDR.PEOPLE_CODE_ID
	,EVENT_CLASS
	,EVENT_ID
