SELECT AR.ASSESSMENT_RULE_ID
	,ACADEMIC_YEAR
	,ACADEMIC_TERM
	,AR.LONG_DESC
	--,AR.HELP_DESC
	--,SECTION_FEE_FLAG
	,CASE 
		WHEN PATINDEX('%STUDENTFINANCIAL.CREDIT_BILLING%', SELECT_CRITERIA) > 0
			THEN SUBSTRING(SELECT_CRITERIA, CHARINDEX('STUDENTFINANCIAL.CREDIT_BILLING', SELECT_CRITERIA) + 31, CHARINDEX(')', SUBSTRING(SELECT_CRITERIA, CHARINDEX('STUDENTFINANCIAL.CREDIT_BILLING', SELECT_CRITERIA) + 31, 1000)) - 1)
		ELSE NULL
		END [Billing Credits Filter]
	,ACC.PER_CREDIT_FLAT
	,ACC.AMOUNT
	,CHARGE_CREDIT_CODE
	,CRG_CRD_DESC
	,CRG_CRD_MED_DESC
	--,AR.STORED_PROC_NAME
	,OVERLOAD
	,COURSE_CREDIT_BASE
--,SELECT_CRITERIA
FROM ASSESSMENTRULE AR
INNER JOIN ASSESSCHARGECREDIT ACC
	ON ACC.ASSESSMENT_RULE_ID = AR.ASSESSMENT_RULE_ID
INNER JOIN CODE_CHARGECREDIT CCC
	ON CCC.CODE_VALUE_KEY = ACC.CHARGE_CREDIT_CODE
WHERE 1 = 1
	AND SECTION_FEE_FLAG = 'N'
	--AND PER_CREDIT_FLAT = 'P'
	--AND ACADEMIC_YEAR = '2021'
	--AND ACADEMIC_TERM = 'SUMMER'
