USE Campus6

BEGIN TRAN

UPDATE TS
SET EDIT_RIGHTS = TS2.EDIT_RIGHTS
	,DELETE_RIGHTS = TS2.DELETE_RIGHTS
--SELECT TS.TABLE_NAME
--	,ts.SECURITY_ID
--	,ts.EDIT_RIGHTS
--	,ts.DELETE_RIGHTS
--	,TS2.TABLE_NAME
--	,TS2.SECURITY_ID
--	,TS2.EDIT_RIGHTS
--	,TS2.DELETE_RIGHTS
FROM ABT_TABLESECURITY TS
LEFT JOIN ABT_TABLESECURITY TS2
	ON TS.TABLE_NAME = TS2.TABLE_NAME
		AND TS2.SECURITY_ID IN ('AWILLIAM')
		AND (
			TS2.EDIT_RIGHTS = 'Y'
			OR TS2.DELETE_RIGHTS = 'Y'
			)
WHERE TS.SECURITY_ID = 'IRDATA'
	AND (
		TS.EDIT_RIGHTS <> TS2.EDIT_RIGHTS
		OR TS.DELETE_RIGHTS <> TS2.DELETE_RIGHTS
		)

ROLLBACK TRAN
